# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  Default
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'D:\test_151122\javaproj/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '18'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    goals: 'package'
    # Windows machine file copy
      # Copy files to remote Windows machines
- task: WindowsMachineFileCopy@2
  inputs:
    sourcePath: D:\test_151122\javaproj\target
    machineNames: 192.168.1.4
    #AdminUserName: VRavi
    #AdminPassword: 
    targetPath: D:\apache-tomcat-10.0.21\webapps
