# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  Default
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'https://github.com/vravi1419/pipelines-java/blob/876f57469226d45f4600765b6764dc4139764cc5/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '18'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    goals: 'package'
